import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient, type ApiSuccessResponse, type PaginatedCollection } from '@/lib/api-client';
import { normalizeFeatureList } from '@/lib/utils';
import type { BillingPage, BillingPayment, BillingPlan, BillingSubscription, PlanInput } from '@/types/billing';

export const BILLING_KEYS = {
    plans: ['billing', 'plans'] as const,
    trialSetting: ['billing', 'trial-setting'] as const,
    subscriptions: (companyId: string) => ['billing', 'subscriptions', companyId] as const,
    payments: (companyId: string, subscriptionId: string, page: number) => ['billing', 'payments', companyId, subscriptionId, page] as const,
} as const;

type PlanDto = { id:number; name:string; slug:string; price_monthly:number|string; price_six_monthly:number|string|null; price_yearly:number|string; max_employees:number|null; max_branches:number|null; features:unknown; is_active:boolean|number; stripe_monthly_price_id:string|null; stripe_six_monthly_price_id:string|null; stripe_yearly_price_id:string|null; subscriptions_count?:number|null };
type SubscriptionDto = { id:number; company_id:number; plan_id:number; status:string; stripe_status:string|null; billing_cycle:'monthly'|'six_month'|'yearly'; starts_at:string|null; ends_at:string|null; trial_ends_at:string|null; cancelled_at:string|null; is_active:boolean; is_cancelled:boolean; on_trial:boolean; plan?:PlanDto|null };
type PaymentDto = { id:number; amount:number|string; amount_refunded:number|string; currency:string; payment_provider:string; provider_reference:string|null; status:string; paid_at:string|null; refunded_at:string|null; is_refundable:boolean; is_refunded:boolean };
type TrialSettingDto = { trial_period_days:number };
const number = (value:number|string|null|undefined) => Number(value ?? 0);
const mapPlan=(d:PlanDto):BillingPlan=>({id:String(d.id),name:d.name,slug:d.slug,priceMonthly:number(d.price_monthly),priceSixMonthly:d.price_six_monthly===null?null:number(d.price_six_monthly),priceYearly:number(d.price_yearly),maxEmployees:d.max_employees,maxBranches:d.max_branches,features:normalizeFeatureList(d.features),isActive:Boolean(d.is_active),stripeMonthlyPriceId:d.stripe_monthly_price_id,stripeSixMonthlyPriceId:d.stripe_six_monthly_price_id,stripeYearlyPriceId:d.stripe_yearly_price_id,subscriptionsCount:d.subscriptions_count??null});
const mapSub=(d:SubscriptionDto):BillingSubscription=>({id:String(d.id),companyId:String(d.company_id),planId:String(d.plan_id),status:d.status,stripeStatus:d.stripe_status,billingCycle:d.billing_cycle,startsAt:d.starts_at,endsAt:d.ends_at,trialEndsAt:d.trial_ends_at,cancelledAt:d.cancelled_at,isActive:d.is_active,isCancelled:d.is_cancelled,onTrial:d.on_trial,plan:d.plan?{id:String(d.plan.id),name:d.plan.name,priceMonthly:number(d.plan.price_monthly),priceSixMonthly:d.plan.price_six_monthly===null?null:number(d.plan.price_six_monthly),priceYearly:number(d.plan.price_yearly)}:null});
const mapPayment=(d:PaymentDto):BillingPayment=>({id:String(d.id),amount:number(d.amount),amountRefunded:number(d.amount_refunded),currency:d.currency,provider:d.payment_provider,reference:d.provider_reference,status:d.status,paidAt:d.paid_at,refundedAt:d.refunded_at,isRefundable:d.is_refundable,isRefunded:d.is_refunded});
const page=<T, D>(payload:PaginatedCollection<D>, map:(dto:D)=>T):BillingPage<T>=>({data:payload.data.map(map),currentPage:payload.meta.current_page,lastPage:payload.meta.last_page,total:payload.meta.total});
const planPayload=(value:PlanInput)=>({name:value.name,slug:value.slug||undefined,price_monthly:value.priceMonthly,price_six_monthly:value.priceSixMonthly,price_yearly:value.priceYearly,max_employees:value.maxEmployees,max_branches:value.maxBranches,features:value.features,is_active:value.isActive,stripe_monthly_price_id:value.stripeMonthlyPriceId,stripe_six_monthly_price_id:value.stripeSixMonthlyPriceId,stripe_yearly_price_id:value.stripeYearlyPriceId,stripe_product_id:value.stripeProductId});

export function useBillingPlans(){return useQuery({queryKey:BILLING_KEYS.plans,queryFn:async()=>{const r=await apiClient.get<ApiSuccessResponse<PaginatedCollection<PlanDto>>>('/plans',{params:{per_page:100}});return page(r.data.data,mapPlan)},staleTime:15_000});}
export function useBillingSubscriptions(companyId:string){return useQuery({queryKey:BILLING_KEYS.subscriptions(companyId),queryFn:async()=>{const r=await apiClient.get<ApiSuccessResponse<PaginatedCollection<SubscriptionDto>>>(`/companies/${companyId}/subscriptions`,{params:{per_page:100}});return page(r.data.data,mapSub)},enabled:Boolean(companyId),staleTime:15_000});}
export function useBillingPayments(companyId:string,subscriptionId:string,pageNumber=1){return useQuery({queryKey:BILLING_KEYS.payments(companyId,subscriptionId,pageNumber),queryFn:async()=>{const r=await apiClient.get<ApiSuccessResponse<PaginatedCollection<PaymentDto>>>(`/companies/${companyId}/subscriptions/${subscriptionId}/payments`,{params:{per_page:20,page:pageNumber}});return page(r.data.data,mapPayment)},enabled:Boolean(companyId&&subscriptionId),placeholderData:keepPreviousData,staleTime:15_000});}
export function useCreatePlan(){const q=useQueryClient();return useMutation({mutationFn:async(value:PlanInput)=>mapPlan((await apiClient.post<ApiSuccessResponse<PlanDto>>('/plans',planPayload(value))).data.data),onSuccess:()=>void q.invalidateQueries({queryKey:BILLING_KEYS.plans})});}
export function useUpdatePlan(){const q=useQueryClient();return useMutation({mutationFn:async({id,value}:{id:string;value:PlanInput})=>mapPlan((await apiClient.put<ApiSuccessResponse<PlanDto>>(`/plans/${id}`,planPayload(value))).data.data),onSuccess:()=>void q.invalidateQueries({queryKey:BILLING_KEYS.plans})});}
export function useCheckoutSubscription(companyId:string){return useMutation({mutationFn:async({planId,billingCycle}:{planId:string;billingCycle:'monthly'|'six_month'|'yearly'})=>{const r=await apiClient.post<ApiSuccessResponse<{checkout_url:string}>>(`/companies/${companyId}/subscriptions`,{plan_id:planId,billing_cycle:billingCycle,checkout:true});return r.data.data.checkout_url;}})}
export function useSubscriptionAction(companyId:string){const q=useQueryClient();return useMutation({mutationFn:async({id,action,planId,billingCycle}:{id:string;action:'cancel'|'resume'|'swap';planId?:string;billingCycle?:'monthly'|'six_month'|'yearly'})=>{const r=await apiClient.post<ApiSuccessResponse<SubscriptionDto>>(`/companies/${companyId}/subscriptions/${id}/${action}`,action==='swap'?{plan_id:planId,billing_cycle:billingCycle}:{});return mapSub(r.data.data)},onSuccess:()=>void q.invalidateQueries({queryKey:BILLING_KEYS.subscriptions(companyId)})});}
export function useRefundPayment(companyId:string,subscriptionId:string){const q=useQueryClient();return useMutation({mutationFn:async({paymentId,amount}:{paymentId:string;amount?:number})=>mapPayment((await apiClient.post<ApiSuccessResponse<PaymentDto>>(`/companies/${companyId}/subscriptions/${subscriptionId}/payments/${paymentId}/refund`,amount?{amount}:{})).data.data),onSuccess:()=>void q.invalidateQueries({queryKey:BILLING_KEYS.payments(companyId,subscriptionId,1)})});}
export function useDeletePlan(){const q=useQueryClient();return useMutation({mutationFn:async(id:string)=>{await apiClient.delete<ApiSuccessResponse<null>>(`/plans/${id}`)},onSuccess:()=>void q.invalidateQueries({queryKey:BILLING_KEYS.plans})});}
export function usePlatformTrialSetting(){return useQuery({queryKey:BILLING_KEYS.trialSetting,queryFn:async()=>{const response=await apiClient.get<ApiSuccessResponse<TrialSettingDto>>('/platform-settings/trial');return response.data.data;},staleTime:15_000});}
export function useUpdatePlatformTrialSetting(){const queryClient=useQueryClient();return useMutation({mutationFn:async(trialPeriodDays:number)=>{const response=await apiClient.put<ApiSuccessResponse<TrialSettingDto>>('/platform-settings/trial',{trial_period_days:trialPeriodDays});return response.data.data;},onSuccess:()=>void queryClient.invalidateQueries({queryKey:BILLING_KEYS.trialSetting})});}
