import { useQuery } from '@tanstack/react-query';
import { ArrowRight, BarChart3, BellRing, CalendarDays, Check, ChevronRight, Clock3, Menu, Play, ShieldCheck, Smartphone, Sparkles, UsersRound, X } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ThemeToggle } from '@/Components/ui/theme-toggle';
import { apiClient, type ApiSuccessResponse } from '@/lib/api-client';
import { normalizeFeatureList } from '@/lib/utils';

// `features` is a JSON column, so it is typed as `unknown` and normalised before
// rendering rather than assumed to be a string array.
interface PublicPlan { id: number; name: string; slug: string; price_monthly: number | string; price_yearly: number | string; max_employees: number | null; max_branches: number | null; features: unknown; }

const money = (value: number | string) => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD', maximumFractionDigits: 0 }).format(Number(value));
const planLabel = (plan: PublicPlan, yearly: boolean) => yearly ? money(plan.price_yearly) : money(plan.price_monthly);
const featureCards = [
    { icon: CalendarDays, title: 'Rosters that make sense', body: 'Build clear weekly rosters, reuse templates and publish schedules in moments.' },
    { icon: UsersRound, title: 'One place for every team', body: 'Keep employee details, roles, availability and leave requests connected.' },
    { icon: BellRing, title: 'Everyone stays in the loop', body: 'Instant alerts make shift changes, approvals and new rosters impossible to miss.' },
    { icon: BarChart3, title: 'Clarity for managers', body: 'See staffing coverage and schedule activity before a gap becomes a problem.' },
];

export default function LandingPage(): JSX.Element {
    const [menuOpen, setMenuOpen] = useState(false); const [yearly, setYearly] = useState(true);
    const plans = useQuery({ queryKey: ['public', 'plans'], queryFn: async () => { const response = await apiClient.get<ApiSuccessResponse<PublicPlan[]>>('/public/plans'); return response.data.data; }, staleTime: 60_000 });
    return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
        <header className="sticky top-0 z-40 border-b border-border/70 bg-background/85 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 lg:px-8"><Link to="/" className="flex items-center gap-2 font-semibold tracking-tight"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary text-primary-foreground shadow-lg shadow-primary/20"><Clock3 className="h-5 w-5" /></span><span>Rosterly</span></Link><nav className="hidden items-center gap-7 text-sm font-medium text-muted-foreground md:flex"><a href="#product" className="hover:text-foreground">Product</a><a href="#mobile" className="hover:text-foreground">Employee app</a><a href="#plans" className="hover:text-foreground">Plans</a></nav><div className="hidden items-center gap-3 md:flex"><ThemeToggle /><Link to="/login" className="px-3 py-2 text-sm font-semibold text-foreground hover:text-primary">Log in</Link><Link to="/get-started" className="inline-flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground shadow-lg shadow-primary/20 transition hover:-translate-y-0.5 hover:bg-primary-hover">Get started<ArrowRight className="h-4 w-4" /></Link></div><div className="flex items-center gap-2 md:hidden"><ThemeToggle /><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="grid h-10 w-10 place-items-center rounded-lg border border-border" aria-label="Toggle navigation">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div></div>{menuOpen && <div className="border-t border-border bg-card px-5 py-4 md:hidden"><nav className="grid gap-3 text-sm font-semibold"><a onClick={() => setMenuOpen(false)} href="#product">Product</a><a onClick={() => setMenuOpen(false)} href="#mobile">Employee app</a><a onClick={() => setMenuOpen(false)} href="#plans">Plans</a><Link to="/login">Log in</Link><Link to="/get-started" className="rounded-lg bg-primary px-4 py-3 text-center text-primary-foreground">Get started</Link></nav></div>}</header>
        <main>
            <section className="relative isolate"><div className="absolute inset-x-0 top-0 -z-10 h-[36rem] bg-[radial-gradient(circle_at_15%_15%,hsl(var(--primary)/0.16),transparent_34%),radial-gradient(circle_at_85%_10%,hsl(var(--info)/0.13),transparent_28%)]" /><div className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-18 lg:grid-cols-[1.03fr_0.97fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-28"><div><div className="inline-flex items-center gap-2 rounded-full border border-primary/15 bg-primary/10 px-3 py-1.5 text-sm font-semibold text-primary"><Sparkles className="h-4 w-4" />The calm way to run a busy team</div><h1 className="mt-6 max-w-3xl text-5xl font-semibold leading-[1.04] tracking-[-0.055em] text-foreground sm:text-6xl lg:text-7xl">Every shift covered.<br /><span className="text-primary">Every person</span> in sync.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Rosterly brings rostering, shifts, leave, staff communications and time-aware planning into one beautifully simple workspace.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/get-started" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground shadow-xl shadow-primary/20 transition hover:-translate-y-0.5 hover:bg-primary-hover">Build your roster<ArrowRight className="h-4 w-4" /></Link><a href="#product" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-border bg-card px-5 text-sm font-semibold text-foreground hover:bg-secondary"><Play className="h-4 w-4 fill-current" />See how it works</a></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted-foreground"><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-success" />Set up in minutes</span><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-success" />Built for Australian teams</span></div></div>
                <div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-5 -z-10 rounded-[2.5rem] bg-primary/10 blur-3xl" /><div className="rounded-[1.8rem] border border-border bg-card p-3 shadow-2xl shadow-foreground/10"><div className="rounded-[1.25rem] bg-muted/45 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-medium text-muted-foreground">THIS WEEK</p><h2 className="text-xl font-semibold">Team coverage</h2></div><button className="rounded-lg bg-card px-3 py-2 text-xs font-semibold shadow-sm">14–20 Aug</button></div><div className="mt-5 grid grid-cols-5 gap-2 text-center text-xs">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].map((day, index) => <div key={day}><p className="mb-2 text-muted-foreground">{day}</p><div className={index === 2 ? 'rounded-xl bg-primary p-2 text-primary-foreground' : 'rounded-xl bg-card p-2'}><p className="text-sm font-bold">{12 + index}</p><p className="mt-1 opacity-75">Aug</p></div></div>)}</div><div className="mt-5 space-y-3">{[{ name: 'Morning service', staff: '8 / 8 covered', color: 'bg-success' }, { name: 'Afternoon floor', staff: '6 / 7 covered', color: 'bg-warning' }, { name: 'Closing shift', staff: '5 / 5 covered', color: 'bg-info' }].map(item => <div key={item.name} className="flex items-center gap-3 rounded-xl bg-card p-3 shadow-sm"><span className={`h-9 w-1 rounded-full ${item.color}`} /><div className="min-w-0 flex-1"><p className="font-semibold">{item.name}</p><p className="text-xs text-muted-foreground">{item.staff}</p></div><ChevronRight className="h-4 w-4 text-muted-foreground" /></div>)}</div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-card p-3"><p className="text-xs text-muted-foreground">Leave requests</p><p className="mt-1 text-2xl font-semibold">06</p></div><div className="rounded-xl bg-primary p-3 text-primary-foreground"><p className="text-xs opacity-75">Published shifts</p><p className="mt-1 text-2xl font-semibold">42</p></div></div></div></div></div></div></section>
            <section id="product" className="border-y border-border bg-card/50 py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold text-primary">ONE CONNECTED WORKSPACE</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Less admin. More confidence in every shift.</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{featureCards.map(card => { const Icon = card.icon; return <article key={card.title} className="group rounded-2xl border border-border bg-background p-6 transition hover:-translate-y-1 hover:shadow-xl hover:shadow-foreground/5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><h3 className="mt-5 font-semibold">{card.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{card.body}</p></article> })}</div></div></section>
            <section id="mobile" className="py-20"><div className="mx-auto grid max-w-6xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div className="relative mx-auto order-2 lg:order-1"><div className="mx-auto w-[17rem] rounded-[2.8rem] border-[7px] border-inverted bg-inverted p-2 shadow-2xl"><div className="overflow-hidden rounded-[2.15rem] bg-background"><div className="flex justify-center py-2"><span className="h-1.5 w-20 rounded-full bg-muted" /></div><div className="bg-primary px-5 pb-6 pt-4 text-primary-foreground"><p className="text-xs opacity-75">Good morning, Alex</p><h3 className="mt-1 text-xl font-semibold">Your week at a glance</h3><div className="mt-5 rounded-2xl bg-primary-foreground/15 p-4"><p className="text-xs opacity-75">NEXT SHIFT</p><p className="mt-2 text-lg font-semibold">Friday · 8:00–16:00</p><p className="mt-1 text-sm opacity-80">Harbour Street Cafe</p></div></div><div className="space-y-3 p-4"><p className="text-xs font-semibold text-muted-foreground">UPDATES</p><div className="rounded-xl bg-muted/65 p-3"><p className="text-sm font-semibold">Roster published</p><p className="mt-1 text-xs text-muted-foreground">Your manager has shared next week.</p></div><div className="rounded-xl bg-muted/65 p-3"><p className="text-sm font-semibold">Leave request approved</p><p className="mt-1 text-xs text-muted-foreground">Enjoy your long weekend.</p></div></div></div></div><div className="absolute bottom-6 right-2 rounded-xl border border-border bg-card p-3 shadow-xl"><BellRing className="h-5 w-5 text-primary" /></div></div><div className="order-1 lg:order-2"><p className="text-sm font-semibold text-primary">FOR EVERY EMPLOYEE</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">A mobile experience your team will actually use.</h2><p className="mt-5 max-w-lg text-lg leading-8 text-muted-foreground">Employees can view rosters, see upcoming shifts, manage availability, request leave and receive important updates without chasing the manager.</p><div className="mt-7 space-y-4">{['View current and upcoming rosters', 'Receive timely changes and approvals', 'Submit leave and availability from anywhere'].map(text => <div key={text} className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-success/10 text-success"><Check className="h-4 w-4" /></span><span className="font-medium">{text}</span></div>)}</div></div></div></section>
            <section id="plans" className="bg-muted/50 py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-primary">SIMPLE, LIVE PRICING</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Choose the plan that fits your team.</h2><p className="mt-3 max-w-xl text-muted-foreground">Plans are managed by your platform administrator and update here automatically.</p></div><button type="button" aria-label="Toggle billing cycle" onClick={() => setYearly(!yearly)} className="inline-flex rounded-xl border border-border bg-card p-1 text-sm font-semibold"><span className={!yearly ? 'rounded-lg bg-primary px-3 py-2 text-primary-foreground' : 'px-3 py-2 text-muted-foreground'}>Monthly</span><span className={yearly ? 'rounded-lg bg-primary px-3 py-2 text-primary-foreground' : 'px-3 py-2 text-muted-foreground'}>Yearly</span></button></div>{plans.isLoading ? <div className="mt-10 grid gap-5 md:grid-cols-3">{[0, 1, 2].map(i => <div key={i} className="h-[26rem] animate-pulse rounded-2xl bg-card" />)}</div> : plans.data?.length ? <div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{plans.data.map((plan, index) => <article key={plan.id} className={`relative flex flex-col rounded-2xl border bg-card p-6 shadow-sm ${index === 1 ? 'border-primary ring-1 ring-primary/30' : 'border-border'}`}>{index === 1 && <span className="absolute -top-3 left-6 rounded-full bg-primary px-3 py-1 text-xs font-semibold text-primary-foreground">Most popular</span>}<h3 className="text-xl font-semibold">{plan.name}</h3><div className="mt-4 flex items-end gap-1"><span className="text-4xl font-semibold tracking-tight">{planLabel(plan, yearly)}</span><span className="pb-1 text-sm text-muted-foreground">/{yearly ? 'year' : 'month'}</span></div><p className="mt-2 text-sm text-muted-foreground">{plan.max_employees ?? 'Unlimited'} employees · {plan.max_branches ?? 'Unlimited'} branches</p><ul className="mt-6 flex-1 space-y-3 text-sm">{normalizeFeatureList(plan.features).slice(0, 6).map(feature => <li key={feature} className="flex gap-2"><Check className="mt-0.5 h-4 w-4 shrink-0 text-success" />{feature}</li>)}</ul><Link to={`/get-started?plan=${encodeURIComponent(String(plan.id))}`} className="mt-7 inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-primary-hover">Get started<ArrowRight className="h-4 w-4" /></Link></article>)}</div> : <div className="mt-10 rounded-2xl border border-dashed border-border bg-card p-10 text-center text-muted-foreground">Plans will appear here when they are published by the platform administrator.</div>}</div></section>
            <section className="py-20"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="rounded-[2rem] bg-inverted px-7 py-12 text-inverted-foreground sm:px-12 sm:py-16"><div className="max-w-2xl"><ShieldCheck className="h-7 w-7 text-primary" /><h2 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">Give your next roster a better starting point.</h2><p className="mt-4 text-lg leading-8 text-inverted-foreground/70">Create your company workspace, add your details, choose a plan and bring your whole team along.</p><Link to="/get-started" className="mt-8 inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground hover:bg-primary-hover">Get started free<ArrowRight className="h-4 w-4" /></Link></div></div></div></section>
        </main><footer className="border-t border-border py-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>© {new Date().getFullYear()} Rosterly. Built for clear teams.</p><div className="flex gap-5"><Link to="/login">Log in</Link><Link to="/get-started">Get started</Link></div></div></footer>
    </div>;
}
